name: Run Polyline tests

on:
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:
  merge_group:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo install cargo-all-features
      - run: cargo build-all-features --verbose
      - run: cargo test-all-features --verbose
